# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e488473cec3fe00f00ec0bc926397446612883dac12dc31a12e6926783e13036cc6cf8855995a5020e26514ddf9a451acaf4a7ef00ee0c388f0983dc989d5f8

test:
  secret_key_base: 44e23740cea354810cef598087bfa2e1c57ba0ccfa40b38d25f75e176977673970d15fc38d37aa4468b997b90006ed5de87ecbfd500598be3c8083494c2deedf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
